name: crm_smart
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+20

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  transparent_image: ^2.0.0
  image_picker: ^0.8.5+2
  modal_progress_hud_nsn: ^0.2.1
  http: ^0.13.4
  group_button: ^5.0.1
  intl: ^0.17.0
  dropdown_search: ^2.0.1
  firebase_messaging: ^12.0.0
  firebase_core: ^1.20.0
  cached_network_image: ^3.2.1
  grouped_list: ^5.1.2
  url_launcher: ^6.1.5
  jiffy: ^5.0.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  charts_flutter: ^0.12.0
  dropdown_button2: ^1.0.0
  flutter_launcher_icons: ^0.9.1
  tuple: ^2.0.1
  async: ^2.8.2
  text_scroll: ^0.1.0
  table_calendar: ^3.0.8
  fancy_shimmer_image: ^2.0.2
  collection: ^1.17.1
  in_date_utils: ^1.2.0+2
  infinite_scroll_pagination: ^4.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_spinkit: ^5.2.0
  flutter_slidable: ^3.0.0
  drag_and_drop_lists: ^0.3.3

  # DI
  get_it: ^7.6.4
  injectable: ^2.3.0

  # Modeling
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # State management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  stream_transform: ^2.1.0

  #client
  dio: ^5.3.2

  # dev
  dartz: ^0.10.1
  logger: ^2.0.2

  #ui
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  custom_searchable_dropdown: ^2.1.1
  file_picker: ^5.5.0
  path: ^1.8.3
  mime: ^1.0.4
  open_file: ^3.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  package_info_plus: ^4.2.0
  store_redirect: ^2.0.1


dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assest/images/image3.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assest/
    - assest/images/


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
    - family: Cairo-Bold
      fonts:
        - asset: fonts/Cairo-Bold.ttf
    - family: Cairo-Light
      fonts:
        - asset: fonts/Cairo-Light.ttf
    - family: Cairo-Regular
      fonts:
        - asset: fonts/Cairo-Regular.ttf
    - family: Cairo-Black
      fonts:
        - asset: fonts/Cairo-Black.ttf
    - family: Cairo-ExtraBold
      fonts:
        - asset: fonts/Cairo-ExtraBold.ttf
    - family: Cairo-ExtraLight
      fonts:
        - asset: fonts/Cairo-ExtraLight.ttf
    - family: Cairo-Medium
      fonts:
        - asset: fonts/Cairo-Medium.ttf
    - family: Cairo-SemiBold
      fonts:
        - asset: fonts/Cairo-SemiBold.ttf