buildscript {
    ext.kotlin_version = '1.8.20'
    repositories {
        google()
        jcenter()
        maven { url "https://maven.google.com" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'//3.5.3
        classpath 'com.google.gms:google-services:4.3.15'//4.3.2-4.3.10-8
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex')) {
                details.useVersion "27.1.1"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

gradle.taskGraph.whenReady { taskGraph ->
    def tasks = taskGraph.getAllTasks()
    def buildTasks = tasks.find { it.name.startsWith('build') && it.getGroup() == 'build' }
    if (buildTasks) {
        tasks.findAll {it.name.startsWith('test')}.each { task ->
            task.enabled = false
        }
    }
}
