// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQVScJ2gMSCwAWh1zTnjtzOk2SGWSjStI',
    appId: '1:102540138446:web:a8933eabd8a1d0cee5fd9f',
    messagingSenderId: '102540138446',
    projectId: 'crmapp-8f9de',
    authDomain: 'crmapp-8f9de.firebaseapp.com',
    storageBucket: 'crmapp-8f9de.firebasestorage.app',
    measurementId: 'G-KJC7EKRNM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPc1bZGUTKYilLcLMJbxd8I4RInrPo8AQ',
    appId: '1:102540138446:android:bc175820eaf396efe5fd9f',
    messagingSenderId: '102540138446',
    projectId: 'crmapp-8f9de',
    storageBucket: 'crmapp-8f9de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWr7Gz4jO77Ra96XVV5ddw48VZeYytxAo',
    appId: '1:102540138446:ios:ddc6c76ac52fbea1e5fd9f',
    messagingSenderId: '102540138446',
    projectId: 'crmapp-8f9de',
    storageBucket: 'crmapp-8f9de.firebasestorage.app',
    iosClientId: '102540138446-ttasu47lgst15l9eb1j6aqtnk1bvse6d.apps.googleusercontent.com',
    iosBundleId: 'com.mpluse.crmsmart',
  );

}